services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - my-movie-dashboard-app:latest
      # Use BuildKit for faster builds
      target: runner