name: Deploy To Cloudflare

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: set-up environment
        run: |
          if [ -n "${{ secrets.DOT_ENV_PROD }}" ]; then
            echo "${{ secrets.DOT_ENV_PROD }}" > .env
            echo "Environment file created successfully"
          else
            echo "Warning: DOT_ENV_PROD secret not found, skipping environment setup"
            echo "Creating basic .env file for build process"
            touch .env
          fi

      - name: build
        run: npx @cloudflare/next-on-pages

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: .vercel/output/static

